cmake_minimum_required(VERSION 4.0)
project(hw2_styleguide C)

set(CMAKE_C_STANDARD 17)

add_executable(array_swap src/hw2_styleguide/array_swap.c)
add_executable(fast_multiplication src/hw2_styleguide/fast_multiplication.c)
add_executable(happy_tickets src/hw2_styleguide/happy_tickets.c)
add_executable(quotient src/hw2_styleguide/quotient.c)
